# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    # http_client:
    #     scoped_clients:
    #         # Get access token
    #         http_client.paypal.auth:
    #             #note that this is a regexp
    #             scope: '%env(PAYPAL_API_REGEXP)%/v1/oauth2/token'
    #             auth_basic: '%env(PAYPAL_CLIENT_ID)%:%env(PAYPAL_SECRET)%'
    #             headers:
    #                 Content-Type: 'application/x-www-form-urlencoded'

    #         # Get Order details
    #         http_client.paypal.order:
    #             scope: '%env(PAYPAL_API_REGEXP)%/v2/checkout/orders/[0-9A-Z]{17}'
    #             headers:
    #                 Content-Type: 'application/json'

    #         # Capture payment
    #         http_client.paypal.payment:
    #             scope: '%env(PAYPAL_API_REGEXP)%/v2/checkout/orders/[0-9A-Z]{17}/capture'
    #             headers:
    #                 Content-Type: 'application/json'
    #                 Prefer: 'return=representation' # To get a complete representation of payment

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
